# Copyright © 2022 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

networks:
  edgex-network:
    driver: bridge
services:
  ms-authentication:
    container_name: automated-checkout_ms-authentication
    depends_on:
      data:
        condition: service_started
      command:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: ms-authentication
    hostname: ms-authentication
    image: automated-checkout/ms-authentication:dev
    networks:
      edgex-network: {}
    ports:
    - 48096:48096/tcp
    restart: always
    ipc: none
    read_only: true
    security_opt:
    - no-new-privileges:true
    logging:
      options: { max-file: "5", max-size: 100m }
    user: 2002:2001
  ms-inventory:
    image: "automated-checkout/ms-inventory:dev"
    container_name: automated-checkout_ms-inventory
    depends_on:
      data:
        condition: service_started
      command:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: ms-inventory
    hostname: ms-inventory
    networks:
      edgex-network: {}
    ports:
    - 48095:48095/tcp
    restart: always
    ipc: none
    security_opt:
    - no-new-privileges:true
    logging:
      options: { max-file: "5", max-size: 100m }
    user: "2000:2000"
  ms-ledger:
    image: "automated-checkout/ms-ledger:dev"
    container_name: automated-checkout_ms-ledger
    depends_on:
      data:
        condition: service_started
      command:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: ms-ledger
      APPLICATIONSETTINGS_INVENTORYENDPOINT: "http://ms-inventory:48095/inventory"
    hostname: ms-ledger
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:48093:48093/tcp
    restart: always
    ipc: none
    security_opt:
    - no-new-privileges:true
    logging:
      options: { max-file: "5", max-size: 100m }
    user: "2000:2000"
  ds-card-reader:
    image: "automated-checkout/ds-card-reader:dev"
    container_name: automated-checkout_ds-card-reader
    depends_on:
      data:
        condition: service_started
      command:
        condition: service_started
      consul:
        condition: service_started
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-mqtt-broker
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: ds-card-reader
    hostname: ds-card-reader
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:48098:48098/tcp
    restart: always
    ipc: none
    security_opt:
    - no-new-privileges:true
    logging:
      options: { max-file: "5", max-size: 100m }
    user: "2000:2000"
version: '3.7'
