# Copyright © 2022 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

networks:
  edgex-network:
    driver: bridge
services:
  ms-authentication:
    container_name: automated-checkout_ms-authentication
    depends_on:
      data:
        condition: service_started
      command:
        condition: service_started
    environment:
      # Comment out and/or update the setting of http_proxy if needed (e.g. not using proxy)
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      # MESSAGEQUEUE_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: ms-authentication
    hostname: ms-authentication
    image: automated-checkout/ms-authentication:dev
    networks:
      edgex-network: {}
    ports:
    - 48096:48096/tcp
    restart: always
    ipc: none
    read_only: true
    security_opt:
    - no-new-privileges:true
    logging:
      options: { max-file: "5", max-size: 100m }
    user: 2002:2001

version: '3.7'
