# Copyright © 2022 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

# Pre-define Devices
[[DeviceList]]
  Name = 'ds-controller-board'
  ProfileName = 'ds-controller-board'
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      #TODO: move protocol properties from configuration.toml to here
    [[DeviceList.AutoEvents]]
      Interval = '3s'
      OnChange = true
      SourceName = 'controller-board-status'