# Copyright © 2022 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause


[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48093
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This microservice exposes a CRUD interface for financial transactions in a ledger'
Timeout = '30s'

[Registry]
Host = "localhost"
Port = 8500
Type = 'consul'

[Trigger]
Type="http"

[AppCustom]
InventoryEndpoint = "http://localhost:48095/inventory"
