# Copyright © 2022 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause


[Writable]
LogLevel = 'INFO'

[Service]
ClientMonitor = '15s'
HealthCheckInterval = '10s'
Host = 'localhost'
Port = 48093
ReadMaxLimit = 100
StartupMsg = 'This microservice exposes a CRUD interface for financial transactions in a ledger'
RequestTimeout = '30s'
MaxRequestSize = 0

[Registry]
Host = "localhost"
Port = 8500
Type = 'consul'

[Trigger]
Type="http"

[ApplicationSettings]
InventoryEndpoint = "http://localhost:48095/inventory"
LedgerFileName = "/tmp/ledger.json"
