# Copyright © 2020 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

[Writable]
LogLevel = 'INFO'

[Service]
Host = 'localhost'
Port = 48097
Protocol = 'http'
ConnectRetries = 100
BootTimeout = 30000
CheckInterval = '10s'
StartupMsg = 'device controller board started'
ReadMaxLimit = 256
Labels = []
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = ''

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081
  Timeout = 5000

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  [Device.Discovery]
    Enabled = false
    Interval = '30s'

[Driver]
  VID = '2341'
  PID = '8037'
  DisplayTimeout = '10s'
  LockTimeout = '30s'
  VirtualControllerBoard = 'true'

# Pre-define Devices
[[DeviceList]]
  Name = 'ds-controller-board'
  Profile = 'ds-controller-board'
  Description = 'ds-controller-board-description'
  Labels = [ 'ds-controller-board-label' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = 'device-scale-01'
      Port = '300'
    [[DeviceList.AutoEvents]]
      Frequency = '3s'
      OnChange = true
      Resource = 'controller-board-status'
