# Copyright © 2020 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause


[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'ms-ledger'
Port = 48093
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This microservice exposes a CRUD interface for financial transactions in a ledger'
Timeout = '30s'

[Clients]
  [Clients.Logging]
  Host = "edgex-support-logging"
  Protocol = "http"
  Port = 48061

[Registry]
Host = "edgex-core-consul"
Port = 8500
Type = 'consul'

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'edgex-core-data'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = true

[Binding]
Type="http"
SubscribeTopic=""
PublishTopic=""

[ApplicationSettings]
InventoryEndpoint = "http://ms-inventory:48095/inventory"
