# Copyright © 2022 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

[Writable]
LogLevel = 'INFO'
    [Writable.InsecureSecrets]
        [Writable.InsecureSecrets.DB]
        path = "redisdb"
            [Writable.InsecureSecrets.DB.Secrets]
            username = ""
            password = ""

[Service]
HealthCheckInterval = '10s'
Host = 'localhost'
Port = 48099
StartupMsg = 'This is an Application Service which reads card inputs and publishes lock status back to message bus'
RequestTimeout = '30s'
MaxRequestSize = 0
ServerBindAddr = ""
MaxResultCount = 0

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Trigger]
Type="edgex-messagebus"
  [Trigger.EdgexMessageBus]
  Type = "mqtt"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 1883
    Protocol = "tcp"
    SubscribeTopics="edgex/events/#"
    [Trigger.EdgexMessageBus.Optional]
    authmode = "none"
    # Default MQTT Specific options that need to be here to enable evnironment variable overrides of them
    ClientId ="as-vending"
    Qos =  "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive =  "10" # Seconds (must be 2 or greater)
    Retained = "false"
    AutoReconnect = "true"
    ConnectTimeout = "5" # Seconds
    SkipCertVerify = "false"

[ApplicationSettings]
  AuthenticationEndpoint = "http://localhost:48096/authentication"
  DeviceControllerBoarddisplayReset = "http://localhost:48082/api/v1/device/name/ds-controller-board/command/displayReset"
  DeviceControllerBoarddisplayRow0 = "http://localhost:48082/api/v1/device/name/device-controller-board/command/displayRow0"
  DeviceControllerBoarddisplayRow1 = "http://localhost:48082/api/v1/device/name/device-controller-board/command/displayRow1"
  DeviceControllerBoarddisplayRow2 = "http://localhost:48082/api/v1/device/name/device-controller-board/command/displayRow2"
  DeviceControllerBoarddisplayRow3 = "http://localhost:48082/api/v1/device/name/device-controller-board/command/displayRow3"
  DeviceControllerBoardLock1 = "http://localhost:48082/api/v1/device/name/device-controller-board/command/lock1"
  DeviceControllerBoardLock2 = "http://localhost:48082/api/v1/device/name/device-controller-board/command/lock2"
  DeviceNames   = "ds-card-reader,Inference-MQTT-device"
  DoorCloseStateTimeout = "20s"
  DoorOpenStateTimeout = "15s"
  InferenceDoorStatus = "http://localhost:48082/api/v1/device/name/Inference-MQTT-device/command/inferenceDoorStatus"
  InferenceHeartbeat = "http://localhost:48082/api/v1/device/name/Inference-MQTT-device/command/inferenceHeartbeat"
  InferenceTimeout = "20s"
  InventoryAuditLogService = "http://localhost:48095/auditlog"
  InventoryService = "http://localhost:48095/inventory/delta"
  LCDRowLength = "19"
  LedgerService = "http://localhost:48093/ledger"
